server:
  name: week02
  port: 8097

db:
  name:     mysql
  user:     root
  password: mysqlPass@123
  database: test

  table:
    user: users
#
#contacts:
#  - name: i test
#    email: test@test.com